services:
  db:
    image: postgres:latest
    container_name: apoia-dev-db
    restart: "no"
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - apoia_dev_db_data:/var/lib/postgresql/data

volumes:
  apoia_dev_db_data:
    external: true
